<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="registrarFormularios" targetNamespace="http://ws.recaudos.esb.ccb.org.co" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.recaudos.esb.ccb.org.co" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema targetNamespace="http://ws.recaudos.esb.ccb.org.co" xmlns:mrm="http://ws.recaudos.esb.ccb.org.co">
			<xsd:include schemaLocation="registrarFormularios.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="Operation1_in">
		<wsdl:part element="tns:registrarFormularios" name="registrarFormularios"/>
	</wsdl:message>
	<wsdl:message name="Operation1_out">
		<wsdl:part element="tns:registrarFormulariosResponse" name="registrarFormulariosResponse"/>
	</wsdl:message>
	<wsdl:portType name="registrarFormulariosPortType">
		<wsdl:operation name="Operation1">
			<wsdl:input message="tns:Operation1_in" name="Operation1_Input"/>
			<wsdl:output message="tns:Operation1_out" name="Operation1_Output"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="registrarFormulariosSOAP_HTTP_Binding" type="tns:registrarFormulariosPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Operation1">
			<soap:operation soapAction=""/>
			<wsdl:input name="Operation1_Input">
				<soap:body parts="registrarFormularios" use="literal"/>
			</wsdl:input>
			<wsdl:output name="Operation1_Output">
				<soap:body parts="registrarFormulariosResponse" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="registrarPagoRM_HTTP_Service">
		<wsdl:port binding="tns:registrarFormulariosSOAP_HTTP_Binding" name="registrarFormularios_HTTP_Port">
			<soap:address location="https://datapower/esb/service/PUP/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>